### ISSUE TITLE
✨ : stack (creation mode) - make specific form fields mandatory

### ISSUE THREAD

**Issue by cdubuisson** [CodeKaio/gaia#73]
**Is your feature request related to a problem? Please describe.**
In the stack screen , some fields should be mandatory:
 - name
 - variables if specified (see #72)

**Describe the solution you'd like**
Make the fields mandatory. If a mandatory field is empty, the input should be highlighted in red and the save should not be executed.
Check the fields in the view and in the controller.

**Describe alternatives you've considered**
In creation mode, the mandatory fields could be autofilled by default from the module fields.

**Additional context**
For the variables part, issue #72 should treated first.

**Comment by juwit** [comment]
see https://bootstrap-vue.js.org/docs/reference/validation
