### ISSUE TITLE
🔒 : add ldap authentication

### ISSUE THREAD

**Issue by juwit** [CodeKaio/gaia#8]
Connecting to a OAuth/OpenId seems complicated and does not allow to fetch user authorities for the application.

Maybe we should think of a simpler system (using a custom auth, with database user storage), and integrate with a LDAP server, as we do in gitlab or sonarqube as an example

**Comment by candidson** [comment]
Hello
any plans on reopening this?

**Comment by juwit** [comment]
Hello.

It has been implemented a long time ago, but not well-tested and documented.
I'll work on the documentation and tests, I open a dedicated issue for that.
