### ISSUE TITLE
🐛 : keep sidebar status when changing route

### ISSUE THREAD

**Issue by cdubuisson** [CodeKaio/gaia#82]
**Describe the bug**
When one a page if the sidebar is collapsed, changing the page makes the sidebar to be expanded. The sidebar should stay collapsed.

**To Reproduce**
1. Go to any page 
2. Click on the sidebar toggle to collapse the left menu
3. Go to any other page
4. The sidebar is expanded again

**Expected behavior**
The status of the sidebar should remained untouched when changing routes.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Arch Linux (kernel 5.2.5-arch1-1)
 - Browser: Firefox Developer Edition 69.0b8 (64-bit)
 - Version: Gaia 1.0.0

**Additional context**
N/A

**Comment by cdubuisson** [comment]
maybe we can store the status of the sidebar in a cookie

**Comment by juwit** [comment]
> maybe we can store the status of the sidebar in a cookie

Yeah, it would be helpful if we like to use it for server-side rendering.
The other solution would be a simple key used in local-storage, but would involve a little JS coding.

Maybe we should make the sidebar a Vue component too? What do you think?

**Comment by cdubuisson** [comment]
Totally agree for making the sidebar a Vue component

**Comment by juwit** [comment]
Gitlab uses a `sidebar_collapsed` cookie to store the status :)
