### ISSUE TITLE
✨ : init mongo database

### ISSUE THREAD

**Issue by cdubuisson** [CodeKaio/gaia#95]
**Is your feature request related to a problem? Please describe.**
Add a js script to initialize data in mongo database. This script can be used to build a specific docker image or can be used as well with TestContainer for integrations tests.

**Describe the solution you'd like**
Create a js script with json data.
Add a new dockerfile to build and run a mongo database with data.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by juwit** [comment]
That would be ~nice~ **great** to be able to use the scripts in a way like :

```java
@Container
private static MongoContainer mongoContainer = new MongoContainer()
    .withScript("data/01-users.js")
    .withScript("data/02-modules.js");
```

Maybe a simple way to do that is to init a `MongoClient` and then execute the scripts which can be found in the classpath?

**Comment by cdubuisson** [comment]
I was thinking of something similar. No more surprise... :cry:
